### PR TITLE
Test/session

### PR DESCRIPTION
**Pull request by mainlyetcetera**
**what does this pr do?**
- adds tests for `session controller` methods

**according to `coverage/index.html`, what coverage achieved?**
- for `sessions_spec.rb`: 100%

### CODE REVIEW

**Comment by mainlyetcetera** [comment]
I attempted to reset my `Gemfile.lock` file after making the pr. It's saying I'm up-to-date with this branch, so perhaps there were no changes. Any other ideas as to a build fail?

Removed the lock with `rm -rf`, and it's allowing me to push this now. Standby.

**Comment by mainlyetcetera** [comment]
Depressingly, still a fail after removing and running `bundle install` again. Any other thoughts?

**Comment by mainlyetcetera** [comment]
Now trying checking out to main, removing the lock, pulling remote main, checking back out to local branch, removing the lock, merging from now-local main, and re-pushing. Looks like it did find the figaro gem; unfortunately still a failed build.

Attempting with committing the removal then re-adding of the lock. Unfortunately, same result.

**Comment by ribbansmax** [comment]
So I pulled it down, deleted the gem file, and bundled again. I think it will work now?

**Comment by ribbansmax** [comment]
I also accidentally added in a few things I was working on on a different branch, please ignore

**Comment by ribbansmax** [comment]
One thing @mainlyetcetera that you might have to do is run ```bundle exec figaro install```

**Pull request merged**
